// Mocks generated by Mockito 5.4.6 from annotations
// in n3rd_game/test/services/friend_score_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:flutter_contacts/flutter_contacts.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:n3rd_game/models/friend.dart' as _i3;
import 'package:n3rd_game/services/friends_service.dart' as _i2;
import 'package:n3rd_game/services/stats/stats_repository.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FriendsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsService extends _i1.Mock implements _i2.FriendsService {
  MockFriendsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Friend> get friends => (super.noSuchMethod(
        Invocation.getter(#friends),
        returnValue: <_i3.Friend>[],
      ) as List<_i3.Friend>);

  @override
  List<_i3.FriendRequest> get pendingRequests => (super.noSuchMethod(
        Invocation.getter(#pendingRequests),
        returnValue: <_i3.FriendRequest>[],
      ) as List<_i3.FriendRequest>);

  @override
  bool get isLoadingMoreFriends => (super.noSuchMethod(
        Invocation.getter(#isLoadingMoreFriends),
        returnValue: false,
      ) as bool);

  @override
  bool get hasMoreFriends => (super.noSuchMethod(
        Invocation.getter(#hasMoreFriends),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshFriends() => (super.noSuchMethod(
        Invocation.method(
          #refreshFriends,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadMoreFriends() => (super.noSuchMethod(
        Invocation.method(
          #loadMoreFriends,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> searchUsers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> sendFriendRequest(
    String? friendUserId, {
    String? friendEmail,
    String? friendDisplayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [friendUserId],
          {
            #friendEmail: friendEmail,
            #friendDisplayName: friendDisplayName,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> acceptFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> rejectFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFriend(String? friendUserId) => (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [friendUserId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> blockUser(String? userIdToBlock) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [userIdToBlock],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unblockUser(String? userIdToUnblock) => (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [userIdToUnblock],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isUserBlocked(String? userIdToCheck) => (super.noSuchMethod(
        Invocation.method(
          #isUserBlocked,
          [userIdToCheck],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getFriendSuggestions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriendSuggestions,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> sendInvitation(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendInvitation,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reportUser(
    String? reportedUserId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportUser,
          [
            reportedUserId,
            reason,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Contact>> getContacts() => (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Contact>>.value(<_i5.Contact>[]),
      ) as _i4.Future<List<_i5.Contact>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> searchContactsAndUsers(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchContactsAndUsers,
          [query],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StatsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsRepository extends _i1.Mock implements _i7.StatsRepository {
  MockStatsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<int?> getHighestScore(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getHighestScore,
          [userId],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<Map<String, int>> getFriendScores(List<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFriendScores,
          [userIds],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);
}
