#!/bin/bash
# Batch typography standardization script
# Replaces GoogleFonts direct calls with AppTypography equivalents

echo "Typography Standardization Script"
echo "=================================="
echo ""
echo "This script helps batch-process typography fixes."
echo "Pattern established in: conversations_screen.dart, login_screen.dart, friends_screen.dart"
echo ""
echo "Remaining files to process:"
echo "  - settings_screen.dart (77 instances)"
echo "  - leaderboard_screen.dart"
echo "  - editions_screen.dart"
echo "  - youth_editions_screen.dart"
echo "  - onboarding_screen.dart"
echo "  - direct_message_screen.dart"
echo "  - terms_of_service_screen.dart"
echo "  - achievements_screen.dart"
echo "  - ai_edition_history_screen.dart"
echo "  - trivia_creator_screen.dart"
echo "  - voice_calibration_screen.dart"
echo "  - analytics_dashboard_screen.dart"
echo "  - subscription_management_screen.dart"
echo "  - multiplayer_lobby_screen.dart"
echo "  - practice_mode_screen.dart"
echo "  - daily_challenges_screen.dart"
echo "  - editions_selection_screen.dart"
echo "  - multiplayer_game_screen.dart"
echo "  - learning_mode_screen.dart"
echo "  - profile_edit_screen.dart"
echo "  - instructions_screen.dart"
echo "  - ai_edition_input_screen.dart"
echo "  - privacy_policy_screen.dart"
echo "  - performance_insights_screen.dart"
echo ""
echo "See TYPOGRAPHY_STANDARDIZATION_GUIDE.md for replacement patterns."
echo ""
echo "Manual process:"
echo "1. Remove 'import package:google_fonts/google_fonts.dart;'"
echo "2. Add 'import package:n3rd_game/theme/app_typography.dart;' if missing"
echo "3. Replace GoogleFonts.playfairDisplay(...) with AppTypography.headlineLarge.copyWith(...)"
echo "4. Replace GoogleFonts.inter(...) with AppTypography.bodyMedium.copyWith(...) or labelLarge/labelSmall"
echo "5. Replace GoogleFonts.lora(...) with AppTypography.bodyLarge.copyWith(...)"
echo ""
echo "Reference implementations:"
echo "  - lib/screens/conversations_screen.dart"
echo "  - lib/screens/login_screen.dart"
echo "  - lib/screens/friends_screen.dart"

